import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.4.2"

    const val androidx_test_espresso: String = "3.3.0"

    const val com_squareup_retrofit2: String = "2.9.0"

    const val com_squareup_okhttp3: String = "4.9.0" // available: "4.9.1"

    const val org_jetbrains_kotlin: String = "1.4.30"

    const val androidx_navigation: String = "2.3.3"

    const val com_squareup_moshi: String = "1.11.0"

    const val androidx_fragment: String = "1.3.0"

    const val com_google_dagger: String = "2.31.2-alpha"

    const val androidx_test: String = "1.3.0"

    const val io_mockk: String = "1.10.5" // available: "1.10.6"

    const val com_android_tools_build_gradle: String = "4.1.2"

    const val androidx_test_ext_junit: String = "1.1.2"

    const val junit_junit: String = "4.13.1" // available: "4.13.2"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val lifecycle_viewmodel_savedstate: String = "2.3.0"

    const val multidex_instrumentation: String = "2.0.0"

    const val lifecycle_viewmodel_ktx: String = "2.3.0"

    const val lifecycle_common_java8: String = "2.2.0" // available: "2.3.0"

    const val lifecycle_livedata_ktx: String = "2.3.0"

    const val lifecycle_runtime_ktx: String = "2.3.0"

    const val leakcanary_android: String = "2.6"

    const val swiperefreshlayout: String = "1.2.0-alpha01"

    const val constraintlayout: String = "2.0.4"

    const val vectordrawable: String = "1.1.0"

    const val core_testing: String = "1.1.1"

    const val lint_gradle: String = "27.1.2"

    const val robolectric: String = "4.5" // available: "4.5.1"

    const val viewbinding: String = "4.1.2"

    const val appcompat: String = "1.2.0"

    const val core_ktx: String = "1.3.2"

    const val material: String = "1.2.1" // available: "1.3.0"

    const val multidex: String = "2.0.1"

    const val turbine: String = "0.3.0" // available: "0.4.0"

    const val ktlint: String = "0.38.1" // available: "0.40.0"

    const val timber: String = "4.7.1"

    const val aapt2: String = "4.1.2-6503028"

    const val truth: String = "1.1.2"

    /**
     * Current version: "6.5"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.8.3"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
